version: '3.3'


services:

  postgres_db:
    container_name: postgres_db
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: meloed
      POSTGRES_PASSWORD: OPmcGLVkDCM!
      POSTGRES_DB: test_task
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meloed -d test_task"]
      interval: 10s
      timeout: 5s
      retries: 5
     

  python_writer:
    container_name: python_writer
    volumes:
      - /opt/TestTask/code:/code
    build: 
      context: .    
      dockerfile: Dockerfile_writer
    ports:
      - "5400:5400"

  
  python_orders_checker:
    container_name: python_orders_checker
    volumes:
      - /opt/TestTask/code:/code
    build: 
      context: .
      dockerfile: Dockerfile_orders_checker
    ports:
      - "5401:5401"
